dist: trusty
osx_image: xcode8.2
sudo: false
language: python

matrix:
  fast_finish: true
  include:
    - os: linux
      python: 3.3
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: nightly
    - os: osx
      python: nightly

install:
  - pip install -r requirements-dev.txt

script:
  - py.test --cov pyffi --cov-report=term tests
  - coverage report --show-missing

after_success:
  - coveralls
  - python setup.py sdist bdist_wheel
  - cd docs && make html && cd ..

notifications:
    email: false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: docs/_build/html
  on:
    branch: update_docs
